### ISSUE TITLE
Project Theme

### ISSUE THREAD

**Issue by thatcherty** [CSCE-A201/Text-Based-Adventure-Name-Pending#2]
Discuss the theme of our final project

**Comment by thatcherty** [comment]
Ideas from Jared: 
- Zombie/post-apocalyptic survival game, including combat, looting, crafting, exploring, etc
- Oregon Trail-style game, which includes resources, random events, health management, hunting etc.
- A sci-fi exploration game where the character explores an area (like another planet, a ship, a building, or whatever) that can include unique encounters (monsters, aliens, etc.).
- An RPG that involves being trapped and solving puzzles to escape.

**Comment by thatcherty** [comment]
I like the idea of a ship or building escape exploration game, gives us an excuse to make the space end and provides a simple goal. We could have a few rooms with puzzles, enemy encounters, and peaceful rooms with randomized loot. I think the player should have health, maybe not be able to regain it though (depending on game length).

### Here is one game concept
- Player has say 10 points of health
- Player is trapped in a building (reason undetermined)
- Player navigates through rooms. When enemies are encountered, a random number is generated. Player picks a number between 1-10. Player looses health equal to the difference between the generated number and chosen number, and player defeats enemy if correct number is chosen. If Player selects wrong number, Game outputs the difference (plus or minus) and player picks a new number (more likely to choose right the second time)
- Player must collect four keys to exit the final door. Keys are in rooms behind enemy encounters. In rooms with keys, consider implementing a puzzle. Exit door location can be randomized, key order is irrelevant.

### Things to consider
- Combat is somewhat boring, think of alternatives. Dice roll like DnD for attack or defence strength
- Could display a map showing players location, only revealing rooms when player enters them. Could show status of room/room type
- Weapons could be added. Maybe start with a random weapon which is used throughout the whole game or pick up new weapons in loot rooms. 
- How long do we want this game. The presentation should be about 10min I think. 1 or 2 floors like this would probably be adequate.
- Do we want a detailed story line or generic?
- Can player regain health?
- In the above scenario, enemies would not have health. Consider changing with combat type

**Comment by Sawyer-W-Anderson** [comment]
We could combine the puzzle RPG idea with the sci-fi space setting set on a spaceship (think Tharsis by choice provisions). Then, the RPG could be the ship itself or a person on the ship, and that would give us a few ways to go about doing it.

Of course i'm down to do anything just let me know

**Comment by thatcherty** [comment]
I'm down for the sci-fi spaceship setting and the addition of puzzles.

What do you think of enemy encounters?

Also, for the premise of the game, maybe the player needs to get to an escape shuttle or take back the ship?

Alternatively, the player could be maneuvering the ship through space in an attempt to deliver a valuable item, running into puzzles/enemies/obstacles.

**Comment by Sawyer-W-Anderson** [comment]
If it's ship-based, you could do enemies based on something similar to Faster Than Light. Otherwise, some type of boarding party, etc., would be smarter if you were an individual person.

Taking back the ship might be a bit ambitious because one person can't run a ship, but I'm sure we could figure it out.

**Comment by jdb907** [comment]
The sci-fi spaceship ideas sound good! Therefore, I think the enemies should probably be aliens. 

Here is my rough idea of this game:
For the premise of the game, I think the player should wake up in a damaged spaceship (maybe with no memory and on another planet) that has been attacked by aliens. So the player must explore the ship and solve puzzles to fix the systems, and defend against enemy encounters, hazards, and take back the ship. I know you say it might be ambitious for one person the run a ship, but it is just a fictional game. If you want, maybe one of the requirements is to find a co-pilot or something. I think this way, it has a simple end goal. And we could add alternate endings if needed.

Also, I wanted to incorporate Thatcher's concepts with the health, combat, and map. I think 10 min is a good length. I like the idea using dice roll for combat. Maybe the player has 100 health and the enemies have around 10-20 health. Maybe weapons can have a multiplier on the dice roll.

Let me know what you guys think about this idea! I am down for anything!

**Comment by thatcherty** [comment]
I like the idea of finding an NPC co-pilot, a good replacement or addition to finding materials/keys to repair or start the ship. We would want to consider if the NPC provides any attack boost, has health, and (if we have different endings) generates a different ending. For multiple endings, it may be best to just incorporate either a failed mission (death/time limit) or a success (met requirements to repair and start ship).

The general layout of the ship could be a longer corridor with many rooms on either side (aim for 1-2min per room), with the cockpit at the very front. The side rooms could be dormitories, engine rooms, supplies rooms (healing items/weapons if applicable). The player would need certain items and room statuses to get the ship running again so going to the cockpit early would not end the game. Enemies could randomly appear in rooms, with a max amount of enemies in the game equal to around 60-70% of the number of rooms. The actual puzzles could be relatively the same from game to game, but we could choose puzzles that can have more random solutions so gameplay is more diversified.

Maybe the game has a time limit or move limit? The ship could be about to explode and you have to gather/repair everything in 10-15min or less or a certain number of moves.

It might be simpler to have only attacking for player and enemy, no defense option. I like weapons multiplying the dice roll, in any case, we will need to be mindful to create a healthy balance for gameplay. 

If you all think it would be helpful, an excel sheet listing out all the ideas with a column for each of us to provide a yes or no for inclusion might help us finalize the requirements. We can also setup a time to meet over Zoom if we are all available. We could use one of the lab time slots to meet if you both are free.

**Comment by thatcherty** [comment]
See the WiKi page https://github.com/CSCE-A201/Text-Based-Adventure-Name-Pending/wiki/7%E2%80%9010%E2%80%902024-Notes for notes on the meeting
