### ISSUE TITLE
Engine Room

### ISSUE THREAD

**Issue by thatcherty** [CSCE-A201/Text-Based-Adventure-Name-Pending#5]
Engines are not working, player must solve a puzzle to fix them
Puzzle requires tool from storage room

Puzzle is undetermined as of now

Player can leave room and go back into the hallway

**Comment by Sawyer-W-Anderson** [comment]
The code is mostly set up and finished. The only thing I was unable to verify as working is the void engine running Options section of the code, as that part of the game has not been coded. I will start the pull request so people can see the code, and we can make changes as needed.

**Comment by thatcherty** [comment]
Engine room class merged into main.cpp. Did not link branch.
